Tweaks docs and GHA (#3)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,11 +8,17 @@ on:
    
 jobs:
   macos:
-    runs-on: macos-11 # macos-latest is still 10.15, which we don't support
+    runs-on: macos-12 # macos-latest is still 10.15, which we don't support
     steps:
-    - uses: actions/checkout@v2
-    - uses: devbotsxyz/xcode-select@v1.1.0
+    - uses: maxim-lobanov/setup-xcode@v1
       with:
-        version: latest
+        xcode-version: latest-stable
+    - uses: actions/checkout@v3
     - name: Build & Test
-      run: xcodebuild -scheme 'GeoMonitor' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13'
+      run: xcodebuild test -scheme 'GeoMonitor' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' -resultBundlePath TestResults
+    - uses: kishikawakatsumi/xcresulttool@v1.7.0
+      with:
+        path: TestResults.xcresult
+      if: success() || failure()
+      # ^ This is important because the action will be run
+      # even if the test fails in the previous step.
